### ISSUE TITLE
Movie Recommender System : Existing Code to PEP-8

### ISSUE THREAD

**Issue by divyanshrai655** [GeekHaven/HacktoberFest-AI#1]
The code added is not in PEP-8 format, convert it to the format. Use an autoformatter library like black, autopep8 or yapf.

**Comment by aarpit1010** [comment]
I want to work on this issue..

**Comment by TamoghnoBhattacharya** [comment]
> I want to work on this issue..

Go ahead. No need for permission. First correct PR will be merged.

**Comment by Parasagrawal** [comment]
I want to work on this issue

**Comment by Parasagrawal** [comment]
code is converted int pep8 using autopep8 library
[iit2019145.zip](https://github.com/GeekHaven/GeektoberFest-AI/files/5358560/iit2019145.zip)
