### ISSUE TITLE
Movie Recommender System : Prepare metadata dataframe

### ISSUE THREAD

**Issue by divyanshrai655** [GeekHaven/HacktoberFest-AI#2]
Use the movies.csv and tags.csv files to generate a data frame containing only 2 columns - movie name, metadata. The metadata column will be generated using the genres field from movies.csv and tag field from tags.csv. Use pandas library to make work easier.

**Comment by aarpit1010** [comment]
Started working

**Comment by Parasagrawal** [comment]
i want to work on this

**Comment by aarpit1010** [comment]
Can I work on this?

**Comment by divyanshrai655** [comment]
Yes @aarpit1010 @Parasagrawal both of you can try this out. First correct PR closes this issue.
