### ISSUE TITLE
Movie Recommender System : Prepare user-movie rating matrix

### ISSUE THREAD

**Issue by divyanshrai655** [GeekHaven/HacktoberFest-AI#3]
Use the ratings.csv file to generate a 2D numpy array whose (i,j)th entry is the rating given by i'th user to j'th movie.

**Comment by JLodha** [comment]
I want to work on this

**Comment by divyanshrai655** [comment]
@JLodha  go on . Anyone else seeking the same permission will be granted, the first satisfactory PR for this will be merged.
