### ISSUE TITLE
Movie Recommender System : Apply Sparse SVD and compute RMSE

### ISSUE THREAD

**Issue by TamoghnoBhattacharya** [GeekHaven/HacktoberFest-AI#31]
We'll start with our collaborative filtering model. This is based on matrix factorization using singular value decomposition (Yes, the one from Linear Algebra). Follow the given procedure -
1. Use the code created in issue #3 to create user rating matrix. You will find it under Movie Recommender System/IIT2019134/rating_matrix.py. 
2. Now apply Sparse SVD available in scipy, to the matrix to get the 3 matrices - U, sigma and V-transpose. Choose the latent factors argument wisely to avoid over-fitting and under-fitting. I recommend using in the range 40-60.
3. Multiply the 3 matrices back together to generate the matrix of predicted ratings.
4. Compute the RMSE, i.e. Root Mean Squared Error between the actual ratings matrix and the predicted ratings matrix, and print it. Note that RMSE is only computed on the values which were not NaN in the original ratings matrix, so be careful.

**Comment by JLodha** [comment]
I want to work on this

**Comment by divyanshrai655** [comment]
@JLodha Go on.

**Comment by aarpit1010** [comment]
@Lazy-Leopard @TamoghnoBhattacharya Actually, I have completed the work on this issue, can I submit the PR?

**Comment by TamoghnoBhattacharya** [comment]
> @Lazy-Leopard @TamoghnoBhattacharya Actually, I have completed the work on this issue, can I submit the PR?

Consult with @JLodha and decide who's going to make the PR first. The first correct PR will be merged, simple as that.

**Comment by JLodha** [comment]
Since I claimed the issue first, though there is no hard and fast rule. I would like to request the admins/collaborator to give me a day more (as per the 2 day policy).
Hoping a positive response.
Thanks

**Comment by divyanshrai655** [comment]
@JLodha Go on,complete it by today.
