### ISSUE TITLE
Data Science : Retrieve Stock Data

### ISSUE THREAD

**Issue by TamoghnoBhattacharya** [GeekHaven/HacktoberFest-AI#5]
Write some Python code to retrieve intraday stock data, that is HLOC (High-Low-Open-Close) data, given a duration of 7 days and interval of 1 minute. Here’s a list of features we expect in every data point at minimum: timestamp, high price, low price, opening price, closing price, volume. Check out yfinance or yahoofinancials modules for Python.

**Comment by devarshshah15** [comment]
Started working.

**Comment by divyanshrai655** [comment]
@devarshshah15 your PRs for this repo won't be considered this is a part of college competition, we will be mentioning it to you when we  are open to everyone.

**Comment by HimanshuJanbandhu** [comment]
Can I work on this?

**Comment by divyanshrai655** [comment]
@HimanshuJanbandhu Go on.

**Comment by HimanshuJanbandhu** [comment]
From where do I have to retrieve the data?
What is HLOC data?

**Comment by europe-asia-america** [comment]
It's given in the first comment in this thread. Please read the threads and the README files in the repo carefully.

> Write some Python code to retrieve intraday stock data, that is HLOC (High-Low-Open-Close) data, given a duration of 7 days and interval of 1 minute. Here’s a list of features we expect in every data point at minimum: timestamp, high price, low price, opening price, closing price, volume. Check out yfinance or yahoofinancials modules for Python.

**Comment by aarpit1010** [comment]
@europe-asia-america @Lazy-Leopard  can I give a try to this issue?

**Comment by divyanshrai655** [comment]
@aarpit1010 go on.

**Comment by Parasagrawal** [comment]
can i try this issue

**Comment by divyanshrai655** [comment]
@Parasagrawal someone has already made a good PR, so that would be the one most probably getting merged.Thanks for interest , try out some other issues.

**Comment by Parasagrawal** [comment]
I almost complete this pr , can you just check it is right or wrong

**Comment by divyanshrai655** [comment]
Ok, @Parasagrawal send it we may even consider merging two PRs.
