### ISSUE TITLE
Data Science : Data Collection

### ISSUE THREAD

**Issue by TamoghnoBhattacharya** [GeekHaven/HacktoberFest-AI#6]
Use the techniques you've learnt in the previous issue to collect data for these 5 kinds of assets -

1. Nifty 50 (NSEI)
2. Multi Commodity Exchange of India Limited (MCX.NS)
3. Ethereum INR (ETH-INR)
4. Dow Jones Industrial Average (^DJI)
5. S&P BSE SENSEX (^BSESN)

Save each of the datasets as an appropriately named CSV file.

**Comment by HimanshuJanbandhu** [comment]
Can I work on this issue.

**Comment by europe-asia-america** [comment]
@HimanshuJanbandhu Good to see you here.

Our aim is for you to use your own code, that you have created for a PR in #5, to collect the data. So you should first do #5, then do this issue.

**Comment by HimanshuJanbandhu** [comment]
Thanks! Applied there.

**Comment by Mu-C00L** [comment]
Can I work on this issue.

**Comment by aarpit1010** [comment]
@Lazy-Leopard @TamoghnoBhattacharya  can I work on this issue please?

**Comment by divyanshrai655** [comment]
@Mu-C00L you are being assigned this , but for this you will need a function which is included in issue #5 , you can develop your function for that or a PR is under consideration you can wait for its approval.
@aarpit1010 you can even work (keep your JSON in Geektober-Main updated hope you have submitted less than 6 PRs for review)

**Comment by aarpit1010** [comment]
> @Mu-C00L you are being assigned this , but for this you will need a function which is included in issue #5 , you can develop your function for that or a PR is under consideration you can wait for its approval.
> @aarpit1010 you can even work (keep your JSON in Geektober-Main updated hope you have submitted less than 6 PRs for review)

@Lazy-Leopard sure, I have still 3 left 😄

**Comment by Parasagrawal** [comment]
can I work on this issue

**Comment by divyanshrai655** [comment]
@Parasagrawal the PR you made is solving this issue only 😅

**Comment by Parasagrawal** [comment]
actually it is for both issue

**Comment by Parasagrawal** [comment]
#5 and #6
