### ISSUE TITLE
XBT Predictors : Generate Clean Data

### ISSUE THREAD

**Issue by TamoghnoBhattacharya** [GeekHaven/HacktoberFest-AI#8]
Clean the dataset and prepare it for use by RL algorithms. Also, specify the actions you have taken by appropriate comments.

**Comment by Mridul20** [comment]
I want to work on this issue

**Comment by aarpit1010** [comment]
I want to work on this issue too

**Comment by Tanish-16** [comment]
I want to work on this issue too

**Comment by divyanshrai655** [comment]
@Tanish-16 Go on. But I advice you to perform this part and go for implementing an RL model and put an PR for issue #9
